const productsData = [
    {
        id: 1,
        name: "Melodrama",
        artist: "Lorde",
        year: "2017",
        genre:["Synth pop","electropopart","pop"],
        rating: 8.8,
        price: 25000,
        category:"2010",
        img: "./img/1.png"
    },
    {
        id: 2,
        name: "Fetch the Bolt Cutters",
        artist: "Fiona Apple",
        year: "2020",
        genre:["Art Pop","Progressive Pop"],
        rating: 10,
        price: 24990,
        category:"2020",
        img: "./img/2.jpg",
    },
    {
        id: 3,
        name: "Post",
        artist: "Björk",
        year: "1995",
        genre:["Art Pop", "Electronic"],
        rating: 10,
        price: 21990,
        category:"1990",
        img: "./img/3.jpg",
    },
    {
        id: 4,
        name: "Locura",
        artist: "Virus",
        year: "1985",
        genre:["Synthpop","New Wave"],
        rating: 9.5,
        price: 15000,
        category:"1980",
        img: "./img/4/jpg",
    },
    {
        id: 5,
        name: "Graduation",
        artist: "Kanye West",
        year: "2007",
        genre:["Pop Rap","Electropop"],
        rating: 8.7,
        price: 27990,
        category:"2000",
        img: "./img/5.jpg",
    },
    {
        id: 6,
        name: "Flower Boy",
        artist: "Tyler, The Creator",
        year: "2017",
        genre:["Experimental Hip Hop","Contemporary R&B"],
        rating: 8.5,
        price: 19990,
        category:"2010",
        img: "./img/6.webp",
    },
    {
        id: 7,
        name: "Portamento",
        artist: "The Drums",
        year: "2011",
        genre:["Indie Pop","Synthpop","Post-Punk"],
        rating: 7.4,
        price: 21990,
        category:"2010",
        img: "./img/7.webp",
    },
    {
        id: 8,
        name: "Tidal",
        artist: "Fiona Apple",
        year: "1996",
        genre:["Piano Rock","Art Pop","Jazz Pop"],
        rating: 9,
        price: 25500,
        category:"1990",
        img: "./img/8.png",
    },
    {
        id: 9,
        name: "Pop 2",
        artist: "Charli XCX",
        year: "2017",
        genre:["Electropop","Hyperpop"],
        rating: 8.4,
        price: 23990,
        category:"2010",
        img: "./img/9.webp",
    },
    {
        id: 10,
        name: " Synchronicity",
        artist: "The Police",
        year: "1983",
        genre:["New Wave","Pop Rock"],
        rating: 7.8,
        price: 23600,
        category:"1980",
        img: "./img/10.webp",
    },
    {
        id: 11,
        name: "Experimental Jet Set, Trash and No Star",
        artist: "Sonic Youth",
        year: "1994",
        genre:["Noise Rock","Alternative Rock"],
        rating: 6.7,
        price: 26000,
        category:"1990",
        img: "./img/11.webp",
    },
    {
        id: 12,
        name: "90125",
        artist: "Yes",
        year: "1983",
        genre:["Pop Rock","Progressive Pop"],
        rating: 7.2,
        price: 24990,
        category:"1980",
        img: "./img/12.png",
    },
    {
        id: 13,
        name: "Hot Space",
        artist: "Queen",
        year: "1982",
        genre:["Pop Rock","Funk"],
        rating: 7.3,
        price: 29990,
        category:"1980",
        img: "./img/13.webp",
    },
    {
        id: 14,
        name: "Sgt. Pepper's Lonely Hearts Club Band",
        artist: "The Beatles",
        year: "1967",
        genre:["Psychedelic Pop","Pop Rock"],
        rating: 10,
        price: 35990,
        category:"1960",
        img: "./img/14.jpg",
    },
    {
        id: 15,
        name: "Pet Sounds",
        artist: "The Beach Boys",
        year: "1966",
        genre:["Baroque Pop"],
        rating: 9.4,
        price: 34990,
        category:"1960",
        img: "./img/15.jpg",
    },
    {
        id: 16,
        name: "Yeezus",
        artist: "Kanye West",
        year: "2013",
        genre:["Experimental Hip Hop"],
        rating: 9.5,
        price: 25990,
        category:"2010",
        img: "./img/16.png",
    },
    {
        id: 17,
        name: "Paul's Boutique",
        artist: "Beastie Boys",
        year: "1989",
        genre:["East Coast Hip Hop","Experimental Hip Hop"],
        rating: 9.5,
        price: 32990,
        category:"1980",
        img: "./img/17.png",
    },
    {
        id: 18,
        name: "Future Listening!",
        artist: "Towa Tei",
        year: "1994",
        genre: ["Nu Jazz","Bossa nova"],
        rating: 7.4,
        price: 17990,
        category:"1990",
        img: "./img/18.jpg",
    },
    {
        id: 19,
        name: "Hounds of Love",
        artist: "Kate Bush",
        year: "1985",
        genre:["Art Pop","Progressive Pop","Baroque Pop"],
        rating: 10,
        price: 24500,
        category:"1980",
        img: "./img/19.png",
    },
    {
        id: 20,
        name: "Post Mortem",
        artist: "Dillom",
        year: "2021",
        genre:["Pop Rap","Hardcore Hip Hop"],
        rating: 8,
        price: 25000,
        category:"2020",
        img: "./img/20.png",
    },
    {
        id: 21,
        name: "Artaud",
        artist: "Pescado Rabioso",
        year: "1973",
        rating: 10,
        price: 13990,
        category:"1970",
        img: "./img/21.webp",
    },
    {
        id: 22,
        name: "Visions",
        artist: "Grimes",
        year: "2012",
        genre: ["Blues Rock","Psychedelic Rock"],
        rating: 8.5,
        price: 20990,
        category:"2010",
        img: "./img/22.png",
    },
    {
        id: 23,
        name: "Rumours",
        artist: "Fleetwood Mac",
        year: "1977",
        genre:["Pop Rock","Soft Rock"],
        rating: 10,
        price: 38000,
        category:"1970",
        img: "./img/23.jpg",
    },
    {
        id: 24,
        name: "Rid of Me",
        artist: "PJ Harvey",
        year: "1993",
        genre:["Alternative Rock"],
        rating: 10,
        price: 25990,
        category:"1990",
        img: "./img/24.jpg",
    },
    {
        id: 25,
        name: "Goo",
        artist: "Sonic Youth",
        year: "1990",
        genre:["Alternative Rock","Noise Rock"],
        rating: 8.5,
        price: 19990,
        category:"1990",
        img: "./img/25.jpg",
    }
]